### ISSUE TITLE
Creating model from ml.net and using in nimbusml getting error 

### ISSUE THREAD

**Issue by vrunda-joshi** [microsoft/NimbusML#476] opened 2020-04-01 06:56 UTC
hi,
I m creating anomaly model using IidSpikeDetector  in ml.net and saved successfully.
Now i m using it in databricks to predict. using below code
```

from nimbusml import Pipeline, FileDataStream
dataset = FileDataStream.read_csv('/dbfs/FileStore/tables/Oil_Pressure_Test_Data.csv',names={0:'PSI'},numeric_dtype=np.float32,header=False)
print((dataset.head(3)))
pipeline = Pipeline()
pipeline.load_model("/dbfs/FileStore/tables/model.zip")
print((pipeline.get_params()))
from nimbusml.timeseries import IidSpikeDetector

scores = pipeline.predict(dataset)
```

and getting below error.

RuntimeError: Error: *** System.InvalidOperationException: 'Choose columns by index has no output column.'

can anyone please help me out

**Comment by antoniovs1029** [comment] 2020-04-01 07:38
Hi. Can you please share your dataset and model so that we can reproduce the issue? thanks!

**Comment by vrunda-joshi** [comment] 2020-04-01 08:14
[model.zip](https://github.com/microsoft/NimbusML/files/4413708/model.zip)
csv data is below

7
49
39
31
36
64
46
24
53
63

**Comment by antoniovs1029** [comment] 2020-04-06 18:43
Thanks.

I think the problem is that you can't call `.predict()` on a pipeline that ends on an `IidSpikeDetector`, because it will try to find one Score column, whereas the IidSpikeDetector provides 3 output columns. So, instead, if you call `.transform()` on the pipeline, it behaves as expected.

Changing the following on your script solved the problem:

```python
pipeline.load_model("model.zip")
output = pipeline.transform(dataset)
print(output)
```

And the output, using the data you provided, is then a follows:
```
    PSI  Prediction.Alert  Prediction.Raw Score  Prediction.P-Value Score
0   7.0               0.0                   7.0              5.000000e-01
1  49.0               0.0                  49.0              1.000000e-08
2  39.0               0.0                  39.0              3.734044e-01
3  31.0               0.0                  31.0              4.649713e-01
4  36.0               0.0                  36.0              4.450097e-01
5  64.0               0.0                  64.0              4.216344e-02
6  46.0               0.0                  46.0              3.751326e-01
7  24.0               0.0                  24.0              2.507814e-01
8  53.0               0.0                  53.0              2.432600e-01
9  63.0               0.0                  63.0              1.406056e-01
```

I will close this issue. Please feel free to reopen if you are still having problems with the solution above.

**Closed by antoniovs1029** 2020-04-06 18:43 UTC
