### ISSUE TITLE
Setting base models in EnsembleClassifier

### ISSUE THREAD

**Issue by justinormont** [microsoft/NimbusML#239] opened 2019-08-20 19:08 UTC
How do I set the base trainers for the EnsembleClassifier / EnsembleRegressor?

I don't see an [example](https://github.com/microsoft/NimbusML/blob/fdfda395c443ddae6fce827118213c35fa0d94c8/src/python/nimbusml/examples/EnsembleRegressor.py#L48-L58) of specifying the base model. And I don't see the parameter for specifying the base model type.

For example, I would like to set the base trainer to be FastTree. I would also like to choose a variety of trainers, for example three LightGBM models with specific parameters and two AveragedPerceptron models.

I was expecting to see a parameter like:
```python
EnsembleClassifier(
    base_models=[ SymSgdBinaryClassifier(number_of_iterations=10), LightGbmBinaryClassifier(number_of_iterations=200), LightGbmBinaryClassifier(number_of_iterations=105) ]
)
```

**Comment by ganik** [comment] 2019-08-22 18:16
@justinormont this is a duplicate of this issue #199 
this needs to be implemented in ML.NET API first

**Closed by ganik** 2019-08-22 18:16 UTC

**Comment by justinormont** [comment] 2019-08-22 18:59
Ok; thanks @ganik.
