### ISSUE TITLE
Documentaton: The pipeline visualization example using viz.js does not work in jupyterlab

### ISSUE THREAD

**Issue by pieths** [microsoft/NimbusML#115] opened 2019-05-30 22:19 UTC
The example code on [this](https://docs.microsoft.com/en-us/nimbusml/tutorials/c_a-visualize-a-pipeline#visualize-with-vizjs) page which demonstrates using viz.js inside of a jupyter notebook does not work inside of jupyterlab. The following error is produced when executing the code.

```console
VM171:3 Uncaught ReferenceError: require is not defined
    at <anonymous>:3:1
    at t.attachWidget (panellayout.js:210)
    at t.insertWidget (panellayout.js:113)
    at _insertOutput (widget.js:335)
    at _.onModelChanged (widget.js:217)
    at m (index.js:475)
    at Object.u [as emit] (index.js:433)
    at e.emit (index.js:106)
    at l._onListChanged (model.js:283)
    at m (index.js:475)
```

**Comment by Stephen0620** [comment] 2019-06-17 23:43
Close it for now, both PH and I couldn't reproduce the bug

**Closed by Stephen0620** 2019-06-17 23:43 UTC
